### PR TITLE
REBEL-209: Disable automatic accessibility labels

### PR DESCRIPTION
**Pull request by sghiassy**
The custom accessibility label's being used by RN make no sense and are causing problems.

### CODE REVIEW

**Comment by sghiassy** [comment]
We'll also need to update the Java side as well @andreipt

**Comment by andreipt** [comment]
@sghiassy do we know if the same issue exists on Android?
I tried to find the equivalent in the Android code but the only thing I found was the setter exposed to the RN side using which you can set the `accessibilityLabel`

```
  @ReactProp(name = PROP_ACCESSIBILITY_LABEL)
  public void setAccessibilityLabel(T view, String accessibilityLabel) {
    view.setContentDescription(accessibilityLabel);
  }
```

I couldn't find anything equivalent to `RCTRecursiveAccessibilityLabel`

**Comment by sghiassy** [comment]
This very easily could be an iOS only issue. 

Basically, on iOS, if we inspect the view hierarchy, we see that RN recursively sets attribute labels automatically which didn't work for us (and just seems stupid in general). 

screen shot 2016-06-23 at 11 54 50 am

If the Android view hierarchy is clean, then you should be good

**Comment by sghiassy** [comment]
mergy?

**Comment by andreipt** [comment]
👍

**Pull request merged**
